Add Release page creation

diff --git a/.github/workflows/packaging.yml b/.github/workflows/packaging.yml
--- a/.github/workflows/packaging.yml
+++ b/.github/workflows/packaging.yml
@@ -12,8 +12,35 @@ on:
         default: "v0.0.0"
 
 jobs:
+  determine-version:
+    name: "Determine version"
+    runs-on: ubuntu-latest
+    outputs:
+      VERSION: ${{ steps.define-version.outputs.VERSION }}
+    steps:
+      - name: Define version
+        id: define-version
+        env:
+          # Use the tag name if it is available, otherwise use the input version.
+          # This enables calling from the GitHub UI.
+          VERSION: ${{ github.event.release.tag_name || inputs.version }}
+        run: |
+          if [ -z "$VERSION" ]; then
+            echo "Could not determine version."
+            exit 1
+          elif [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "VERSION must follow the format of 'vX.Y.Z'. Value: '$VERSION'."
+            exit 2
+          fi
+
+          # Export the version to be used in the following jobs.
+          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
+
   package:
     name: "Packaging for ${{ matrix.platform.arch }}-${{ matrix.platform.os }}"
+    needs: determine-version
+    env:
+      VERSION: ${{ needs.determine-version.outputs.VERSION }}
     strategy:
       fail-fast: false
       matrix:
@@ -42,23 +69,6 @@ jobs:
 
     runs-on: ${{ matrix.platform.builder }}
     steps:
-      - name: Define version
-        env:
-          # Use the tag name if it is available, otherwise use the input version.
-          # This enables calling from the GitHub UI.
-          VERSION: ${{ github.event.release.tag_name || inputs.version }}
-        run: |
-          if [ -z "$VERSION" ]; then
-            echo "VERSION not set."
-            exit 1
-          elif [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "VERSION must follow the format of 'vX.Y.Z'. Value: '$VERSION'."
-            exit 2
-          fi
-
-          # Export the version to be used in the following steps.
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
-
       - name: Checkout
         uses: actions/checkout@v3
 
@@ -89,6 +99,8 @@ jobs:
       - name: Upload RPM
         if: matrix.platform.os == 'linux'
         uses: actions/upload-artifact@v4
+        env:
+          VERSION: ${{ steps.determine-version.outputs.VERSION }}
         with:
           name: "nomos-node_${{ env.VERSION }}_${{ matrix.platform.arch }}.rpm"
           path: "target/${{ matrix.platform.target_triple }}/debug/bundle/rpm/nomos-node-${{ env.VERSION }}-.x86_64.rpm"
@@ -125,3 +137,87 @@ jobs:
           name: "nomos-node_${{ env.VERSION }}_${{ matrix.platform.arch }}.msi"
           path: "target/${{ matrix.platform.target_triple }}/debug/bundle/msi/nomos-node_${{ env.VERSION }}_amd64.msi"
           if-no-files-found: error
+
+  release:
+    name: "Create release"
+    needs:
+      - determine-version # Implicit dependency due to `package` also needing it
+      - package
+    runs-on: ubuntu-latest
+    env:
+      VERSION: ${{ needs.determine-version.outputs.VERSION }}
+    steps:
+      - name: Download artifacts
+        uses: actions/download-artifact@v4
+
+      - name: Create Release
+        uses: actions/create-release@v1
+        id: create_release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ env.VERSION }}
+          release_name: Nomos Node ${{ env.VERSION }}
+          body: |
+            This is the release of Nomos Node ${{ env.VERSION }}.
+            ## Changelog
+            - feature(X): new feature
+            - fix(Y): bug description
+            - feature: performance improvement on Z
+          draft: true
+          prerelease: false
+
+      - name: Upload RPM asset
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BINARY_NAME: nomos-node_${{ env.VERSION }}_amd64.rpm
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ github.workspace }}/${{ env.BINARY_NAME }}
+          asset_name: ${{ env.BINARY_NAME }}
+          asset_content_type: application/x-rpm
+
+      - name: Upload DEB asset
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BINARY_NAME: nomos-node_${{ env.VERSION }}_amd64.deb
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ github.workspace }}/${{ env.BINARY_NAME }}
+          asset_name: ${{ env.BINARY_NAME }}
+          asset_content_type: application/x-deb
+
+      - name: Upload AppImage asset
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BINARY_NAME: nomos-node_${{ env.VERSION }}_amd64.AppImage
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ github.workspace }}/${{ env.BINARY_NAME }}
+          asset_name: ${{ env.BINARY_NAME }}
+          asset_content_type: application/x-AppImage
+
+      - name: Upload DMG asset
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BINARY_NAME: nomos-node_${{ env.VERSION }}_${{ matrix.platform.arch }}.dmg
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ github.workspace }}/${{ env.BINARY_NAME }}
+          asset_name: ${{ env.BINARY_NAME }}
+          asset_content_type: application/x-dmg
+
+      - name: Upload MSI asset
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BINARY_NAME: nomos-node_${{ env.VERSION }}_amd64.msi
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ github.workspace }}/${{ env.BINARY_NAME }}
+          asset_name: ${{ env.BINARY_NAME }}
+          asset_content_type: application/x-msi
